version: "3.8"
services:
  nest-exporter:
    build: .
    ports:
      - "5005:80"
    volumes:
      - $HOME/.microsoft/usersecrets:/root/.microsoft/usersecrets/
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
