name: Build

on:
  push:
    paths-ignore:
      - '**.md'
      - '.github/renovate.json'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Lint
      run: | 
        make lint
    
    - name: Build
      run: | 
        make build-all-platforms

    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v2
      with:
        username: theeadie
        password: ${{ secrets.DockerHubAccessToken }}

    - name: Release
      if: github.ref == 'refs/heads/main'
      run: |
        make release GITHUB_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}